---

- name: install key
  apt_key:
    url: "{{ mongodb_apt_key_url }}"
    state: present
  register: mongodb_key_installed

- name: add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: no
  when: mongodb_key_installed|success
  register: mongodb_repo_installed
  with_items: "{{ mongodb_apt_repositories }}"

- name: update apt cache
  apt:
    update_cache: yes
  when: mongodb_repo_installed|changed

- name: install packages
  apt:
    name: "{{ item }}"
    state: latest
    install_recommends: no
    update_cache: yes
    cache_valid_time: 86400
  when: mongodb_repo_installed|success
  with_items: "{{ mongodb_packages }}"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
  with_items:
    - mongod.conf
  notify:
    - restart mongodb
  tags: mongodb_config

- name: service start
  service:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ mongodb_daemon }}"
