---

- name: install packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items:
    - mongodb
    - python-pymongo

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
  with_items:
    - mongodb.conf
  notify:
    - restart mongodb

- name: service start
  service:
    name:  "{{ item }}"
    state: started
  with_items:
    - mongodb
