---

- name: install key
  apt_key:
    url: "{{ mongodb_apt_key_url }}"
    state: present

- name: add repos
  apt_repository:
    repo: "{{ item }}"
    state: present
    update_cache: yes
  with_items: "{{ mongodb_apt_repositories }}"

- name: install packages
  apt:
    name:  "{{ item }}"
    state:              latest
    install_recommends: false
    update_cache:       yes
    cache_valid_time:   300
  with_items: "{{ mongodb_packages }}"

- name: config
  template:
    src: "{{ item }}.j2"
    dest: "/etc/{{ item }}"
    owner: root
    group: root
  with_items:
    - mongod.conf
  notify:
    - restart mongodb
  tags: mongodb_config

- name: service start
  service:
    name:  "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ mongodb_daemon }}"
